In [4]:
pd.__version__

'1.4.4'

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 17:37:40--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M   932KB/s    in 1.5s    

2023-09-18 17:37:43 (932 KB/s) - ‘housing.csv’ saved [1423529/1423529]



In [8]:
data = pd.read_csv('housing.csv')

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [11]:
data.ocean_proximity.nunique()

5

In [19]:
data[data.ocean_proximity == 'NEAR BAY'].describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2290.000000  2290.000000  2290.000000    2290.000000   
mean      2773.555125  1230.317467   488.616157       4.172885   
std      24078.577681   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        290.000000   718.250000   275.000000       2.834750   
50%        425.500000  1033.500000   406.000000       3.818650   
75%        641.000000  1495.000000   599.250000       5.054425   
max     259212.311790  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [16]:
data.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [18]:
data.total_bedrooms.fillna(259212.311790, inplace=True)

In [22]:
data_7 = data[data.ocean_proximity == 'ISLAND'][[ 'housing_median_age', 'total_rooms', 'total_bedrooms']]

In [36]:
data_7

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [26]:
import numpy as np
X = np.array(data_7)

In [27]:
np.transpose(X)

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [42]:
XTX = np.matmul(np.transpose(X), X)

In [43]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [44]:
inv_XTX = np.linalg.inv(XTX)

In [45]:
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [46]:
y = np.array([950, 1300, 800, 1000, 1300])

In [47]:
y

array([ 950, 1300,  800, 1000, 1300])

In [49]:
np.matmul(np.matmul(inv_XTX, np.transpose(X)), y)

array([23.12330961, -1.48124183,  5.69922946])

In [35]:
np.matmul(inv_XTX, y)

array([-7.58655463e+11, -6.48844877e+14,  7.00208219e+14, -3.75147177e+14,
        5.81284246e+14])